# Generated by Django 6.0.4 on 2026-06-29 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_location_job_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_level',
            field=models.CharField(blank=True, choices=[('ENTRY', '0-1 Years'), ('MID', '1-3 Years'), ('SENIOR', '3-5 Years'), ('LEAD', '5+ Years')], max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='employment_type',
            field=models.CharField(choices=[('FULL_TIME', 'Full Time'), ('PART_TIME', 'Part Time'), ('INTERNSHIP', 'Internship'), ('CONTRACT', 'Contract'), ('REMOTE', 'Remote')], max_length=20),
        ),
    ]
